export default [
  "React",
  "VPN",
  "Denial Of Service",
  "TLS",
  "SSL",
  "http",
  "Dependency",
  "HTML",
  "CSS",
  "stack",
  "heap",
  "debugging",
  "bubble sort",
  "Polymorphism",
  "heap",
  "Programmig",
  "fullstack",
  "Rubberduck",
  "Alice",
  "Bob",
  "Firewall",
  "Java",
  "loop",
  "ifelse",
  "public",
  "src",
  "private",
  "modules",
  "Function components",
  "Class components",
  "virtual DOM",
  "reflection",
  "Production",
  "release",
  "backend",
  "OOP",
  "OOD",
  "SQL",
  "Cloud",
  "QA",
  "AWS",
  "DevOps",
  "frontend",
  "Design",
  "senior",
  "junior",
  "entry level",
  "NoSQL",
  "Firebase",
  "Database",
  "recursion",
  "Stack overflow",
  "geeks for geeks",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "duck",
  "Calculus",
  "Data security",
  "Encryption",
  "The seven layer model",
  "Singleton",
  "integrity",
  "confidentiality",
  "availability",
  "CIA",
  "XSS",
  "sql injection",
  "SandBox",
  "Same origin policy",
  "Block cipher",
  "Brute force",
  "Stream cipher",
  "Hash Map",
  "Birthday Paradox",
  "RSA",
  "BFS",
  "DFS",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "Sort",
  "SOLID",
  "switch case",
  "break",
  "running time", 
  "Linear time",
  "Logarithmic time",
  "Exponential time",
  "counting sort",
  "merge sort",
  "Quick sorting",
  "Wen diagram",
  "Truth table",
  "Induction",
  "Regular expression",
  "Turing machine",
  "Linear copies",
  "Deterministic",
  "integral",
  "package",
  "setup",
  "terminal",
  "Linux",
  "manifest",
  "Cantor Lemma",
  "Taylor columns",
  "Leibniz",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "Joseph Louis Lagrange",
  "Newton"
];
